openapi: 3.0.1
info:
  title: Shopping Cart API Documentation
  description: API for managing shopping carts in an e-commerce application.
  version: 1.0.0
servers:
  - url: http://localhost:8080

paths:
  /cart:
    get:
      summary: Get user's cart
      tags:
        - Carts
      security:
        - BearerAuth: [] # Specify JWT security if necessary
      responses:
        "200":
          description: User's cart retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  userId:
                    type: string
                    description: User ID
                  products:
                    type: array
                    items:
                      $ref: "#/components/schemas/Product"
        "401":
          description: Unauthorized

  /cart/add/{productId}:
    post:
      summary: Add a product to the cart
      tags:
        - Carts
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
            description: ID of the product to add
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
            description: JWT authorization token
      responses:
        "200":
          description: Product added to cart successfully
        "401":
          description: Unauthorized
        "404":
          description: Product not found

  /cart/delete/{productId}:
    delete:
      summary: Remove a product from the cart
      tags:
        - Carts
      parameters:
        - in: path
          name: productId
          required: true
          schema:
            type: string
            description: ID of the product to remove from the cart
        - in: header
          name: Authorization
          required: true
          schema:
            type: string
            description: JWT authorization token
      responses:
        "200":
          description: Product removed from cart successfully
        "401":
          description: Unauthorized
        "404":
          description: Product not found

  /cart/increase/{cartId}/{productId}:
    post:
      summary: Increase product quantity in the cart
      tags:
        - Carts
      parameters:
        - in: path
          name: cartId
          required: true
          schema:
            type: string
            description: ID of the cart
        - in: path
          name: productId
          required: true
          schema:
            type: string
            description: ID of the product in the cart
      responses:
        "200":
          description: Product quantity increased in the cart successfully
        "404":
          description: Product not found

  /cart/decrease/{cartId}/{productId}:
    post:
      summary: Decrease product quantity in the cart
      tags:
        - Carts
      parameters:
        - in: path
          name: cartId
          required: true
          schema:
            type: string
            description: ID of the cart
        - in: path
          name: productId
          required: true
          schema:
            type: string
            description: ID of the product in the cart
      responses:
        "200":
          description: Product quantity decreased in the cart successfully
        "404":
          description: Product not found

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          description: Product ID
        title:
          type: string
          description: Product name
        price:
          type: number
          description: Product price
        description:
          type: string
          description: Product description
        imageUrl:
          type: string
          description: Product image URL
        category:
          type: string
          description: Product category
