services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    env_file:
      - .env.production
    restart: always

  mongo:
    image: mongo
    container_name: ecommerce-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
